version: '3.9'

services:

  mongo:
    image: mongo
    #restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip",  "0.0.0.0", "--replSet", "rs0" ]
    hostname: my_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    #restart: always
    depends_on:
      - mongo

    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://my_mongo:27017/?replicaSet=rs0&directConnection=true

  app:
    image: "python:slim"
    #restart: always
    working_dir: "/app"
    ports:
      - '8000:8000'
    env_file:
      - "../.env"
    volumes:
      - "../:/app"
    command: >
      bash -c "
      pip install -r requirements.txt
      && bash run-app.bash
      "
